In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.Series(np.random.uniform(size=9), index=[["a", "a", "a", "b", "b", "c", "c", "d", "d"],
                     [1, 2, 3, 1, 3, 1, 2, 2, 3]])

In [3]:
data #prettified view of Multi Index

a  1    0.218681
   2    0.529726
   3    0.297279
b  1    0.826990
   3    0.438684
c  1    0.048184
   2    0.565617
d  2    0.022458
   3    0.229236
dtype: float64

In [4]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [5]:
data['b']

1    0.826990
3    0.438684
dtype: float64

In [6]:
data['a':'c']

a  1    0.218681
   2    0.529726
   3    0.297279
b  1    0.826990
   3    0.438684
c  1    0.048184
   2    0.565617
dtype: float64

In [7]:
data.loc[["b", "d"]]

b  1    0.826990
   3    0.438684
d  2    0.022458
   3    0.229236
dtype: float64

In [8]:
data[:, 2]

a    0.529726
c    0.565617
d    0.022458
dtype: float64

In [9]:
data.unstack()

1         2         3
a  0.218681  0.529726  0.297279
b  0.826990       NaN  0.438684
c  0.048184  0.565617       NaN
d       NaN  0.022458  0.229236

In [10]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)), index=[["a", "a", "b", "b"], [1, 2, 1, 2]],
                         columns=[["Ohio", "Ohio", "Colorado"],
                            ["Green", "Red", "Green"]])


In [11]:
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [12]:
frame.index.names = ['key1', 'key2']

In [13]:
frame.columns.names = ['state', 'color']

In [14]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [15]:
# To see how many levels an index has
frame.index.nlevels

2

In [16]:
frame['Ohio']['Green'].loc[('a',2)]

3

In [17]:
frame.swaplevel('key1', 'key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [18]:
frame.sort_index()

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [19]:
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [20]:
frame.sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [21]:
frame.sort_index(level=2) #levels too start from zero

IndexError: Too many levels: Index has only 2 levels, not 3

In [22]:
frame.swaplevel(0,1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [23]:
frame = pd.DataFrame({"a": range(7), "b": range(7, 0, -1),
                          "c": ["one", "one", "one", "two", "two",
                                "two", "two"],
                          "d": [0, 1, 2, 0, 1, 2, 3]})

In [24]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [25]:
frame2 = frame.set_index(['c', 'd'])

In [26]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [27]:
frame3 = frame.set_index(['c', 'd'], drop=False)

In [28]:
frame3

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [34]:
arr = np.arange(12).reshape((3, 4))

In [35]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
np.concatenate([arr, arr], axis =1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [39]:
s1 = pd.Series([0, 1], index=["a", "b"], dtype="Int64")
s2 = pd.Series([2, 3, 4], index=["c", "d", "e"], dtype="Int64")
s3 = pd.Series([5, 6], index=["f", "g"], dtype="Int64")

In [41]:
s1

a    0
b    1
dtype: Int64

In [44]:
s2

c    2
d    3
e    4
dtype: Int64

In [45]:
s3

f    5
g    6
dtype: Int64

In [46]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: Int64

In [47]:
pd.concat([s1, s2, s3], axis='columns')

0     1     2
a     0  <NA>  <NA>
b     1  <NA>  <NA>
c  <NA>     2  <NA>
d  <NA>     3  <NA>
e  <NA>     4  <NA>
f  <NA>  <NA>     5
g  <NA>  <NA>     6

In [48]:
s4 = pd.concat([s1, s3])

In [51]:
s4

a    0
b    1
f    5
g    6
dtype: Int64

In [53]:
s1

a    0
b    1
dtype: Int64

In [52]:
pd.concat([s1, s4], axis='columns')

0  1
a     0  0
b     1  1
f  <NA>  5
g  <NA>  6

In [55]:
pd.concat([s1, s4], axis = 'columns', join ='inner')

0  1
a  0  0
b  1  1

In [64]:
result = pd.concat([s1, s2, s3], keys=['one', 'two', 'three', 'four'])

In [65]:
result

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: Int64

In [66]:
result.unstack()

a     b     c     d     e     f     g
one       0     1  <NA>  <NA>  <NA>  <NA>  <NA>
two    <NA>  <NA>     2     3     4  <NA>  <NA>
three  <NA>  <NA>  <NA>  <NA>  <NA>     5     6

In [67]:
result1 = pd.concat([s1, s2, s3], keys=['one', 'two', 'three', 'four'], axis='columns')

In [68]:
result1

one   two  three
a     0  <NA>   <NA>
b     1  <NA>   <NA>
c  <NA>     2   <NA>
d  <NA>     3   <NA>
e  <NA>     4   <NA>
f  <NA>  <NA>      5
g  <NA>  <NA>      6

In [69]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=["a", "b", "c"],
                       columns=["one", "two"])

In [70]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=["a", "c"], columns=["three", "four"])

In [71]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [72]:
df2

three  four
a      5     6
c      7     8

In [76]:
pd.concat([df1, df2], axis='columns', keys=['level1', 'level2'])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [77]:
pd.concat([df1, df2], axis='columns', keys=['level1', 'level2'], names = ['upper', 'lower'])

upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [82]:
df1 = pd.DataFrame(np.random.standard_normal((3,4)), columns=['a', 'b', 'c', 'd'])

In [83]:
df1

a         b         c         d
0 -0.101385  0.697718  0.711688 -0.411572
1 -0.121008  0.083488 -0.979614  0.333193
2 -0.377904 -0.399684  0.203149 -0.882535

In [84]:
df2 = pd.DataFrame(np.random.standard_normal((2,3)), columns=['b', 'd', 'a'])

In [85]:
df2

b         d         a
0 -0.408182 -0.855266  0.701904
1 -0.347324  0.554870  0.717027

In [87]:
a = pd.Series([np.nan, 2.5, 0.0, 3.5, 4.5, np.nan],
                  index=["f", "e", "d", "c", "b", "a"])

In [88]:
b = pd.Series([0., np.nan, 2., np.nan, np.nan, 5.],
                  index=["a", "b", "c", "d", "e", "f"])

In [90]:
a

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [91]:
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [95]:
np.where(pd.isna(a), b, a)

array([0. , 2.5, 0. , 3.5, 4.5, 5. ])

In [96]:
len(np.where(pd.isna(a), b, a))

6

In [97]:
len(b)

6

In [98]:
len(a)

6

In [99]:
a.combine_first(b)

a    0.0
b    4.5
c    3.5
d    0.0
e    2.5
f    5.0
dtype: float64

In [100]:
df1 = pd.DataFrame({"a": [1., np.nan, 5., np.nan],
                      "b": [np.nan, 2., np.nan, 6.],
                      "c": range(2, 18, 4)})

In [101]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [104]:
df2 = pd.DataFrame({"a": [5., 4., np.nan, 3., 7.],
                     "b": [np.nan, 3., 4., 6., 8.]})

In [105]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [106]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [107]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                        index=pd.Index(["Ohio", "Colorado"], name="state"),
                        columns=pd.Index(["one", "two", "three"],
                        name="number"))

In [108]:
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [109]:
result = data.stack()

In [110]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [111]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [112]:
result.unstack(level=0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [113]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [114]:
result.unstack(level="state")

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5