In [1]:
import numpy as np

In [3]:
my_arr = np.arange(1_000_000)

In [4]:
my_list = list(range(1_000_000))

In [5]:
%timeit myarr2 = my_arr * 2

693 µs ± 7.16 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
%timeit my_list2 = [x*2 for x in my_list]

36.6 ms ± 469 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [8]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [9]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [10]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [13]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [14]:
a = np.array(data2)

In [15]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
a.shape

(2, 4)

In [17]:
a.ndim

2

In [18]:
data.dtype

dtype('float64')

In [19]:
a.dtype

dtype('int64')

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.empty(2)

array([-2.00000000e+000,  6.95257223e-310])

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [31]:
np.full(5, 3)

array([3, 3, 3, 3, 3])

In [34]:
np.full_like(data, 5)

array([[5., 5., 5.],
       [5., 5., 5.]])

In [37]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
np.ones((3,4), 'int64')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [58]:
num_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [59]:
num_strings.dtype

dtype('S4')

In [53]:
alpha_arr = num_strings.astype(np.float64)

In [54]:
alpha_arr

array([ 1.25, -9.6 , 42.  ])

In [55]:
alpha_arr.dtype

dtype('float64')

In [64]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])

In [65]:
arr[2:5]

array([2, 3, 4])

In [66]:
arr_slice = arr[2:5]

In [67]:
arr_slice

array([2, 3, 4])

In [68]:
arr_slice[1] = 12345

In [69]:
arr_slice

array([    2, 12345,     4])

In [70]:
arr

array([    0,     1,     2, 12345,     4,     5,     6,     7,     8,
           9,    10])

In [71]:

arr_slice[:] = 786


In [72]:
arr

array([  0,   1, 786, 786, 786,   5,   6,   7,   8,   9,  10])

In [89]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


In [90]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [92]:
old_values = arr3d[0].copy()

In [93]:
arr3d[0] = 43

In [94]:
arr3d

array([[[43, 43, 43],
        [43, 43, 43]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [95]:
arr3d[0] = old_values

In [96]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [97]:
arr3d[1,0]

array([7, 8, 9])

In [98]:
arr

array([  0,   1, 786, 786, 786,   5,   6,   7,   8,   9,  10])

In [99]:
arr[2:6]

array([786, 786, 786,   5])

In [101]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [102]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
arr2d[1]

array([4, 5, 6])

In [107]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [108]:
arr2d[0,2]

3

In [111]:
lower_dim_slice = arr2d[2, :2]

In [112]:
lower_dim_slice

array([7, 8])

In [113]:
lower_dim_slice.shape

(2,)

In [114]:
arr2d.shape

(3, 3)

In [117]:
arr2d[:2,2]

array([3, 6])

In [119]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [120]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [162]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

In [147]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [148]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [149]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [150]:
data[names == 'Bob']

array([[4, 7],
       [0, 0]])

In [151]:
data[names=='Bob', 1:]

array([[7],
       [0]])

In [152]:
data[names=='Bob', 1]

array([7, 0])

In [153]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [154]:
~(names == 'Bob')

array([False,  True,  True, False,  True,  True,  True])

In [155]:
data[~(names == 'Bob')]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [141]:
mask = (names == "Bob") | (names == "Will")

In [156]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [157]:
data[data<0]

array([ -5, -12,  -4])

In [158]:
data[data<0] = 0

In [159]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [163]:
data[names != 'Joe'] = 7

In [164]:
data

array([[  7,   7],
       [  0,   2],
       [  7,   7],
       [  7,   7],
       [  7,   7],
       [-12,  -4],
       [  3,   4]])

In [165]:
arr = np.zeros((8, 4))

In [166]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [167]:
for i in range(8):
    arr[i]= i

In [168]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [169]:
arr = arr.astype(dtype='int64')

In [170]:
arr

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [173]:
arr[[2]] = 44

In [174]:
arr[3] = 56

In [175]:
arr[[2,3,4]]

array([[44, 44, 44, 44],
       [56, 56, 56, 56],
       [ 4,  4,  4,  4]])

In [176]:
arr

array([[ 0,  0,  0,  0],
       [ 1,  1,  1,  1],
       [44, 44, 44, 44],
       [56, 56, 56, 56],
       [ 4,  4,  4,  4],
       [ 5,  5,  5,  5],
       [ 6,  6,  6,  6],
       [ 7,  7,  7,  7]])

In [177]:
arr[-1]

array([7, 7, 7, 7])

In [178]:
arr[[-1,-2,-3]]

array([[7, 7, 7, 7],
       [6, 6, 6, 6],
       [5, 5, 5, 5]])

In [180]:
arr = np.arange(32).reshape((8,4))

In [181]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [182]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [185]:
arr[[1, 5, 7, 2]][[0, 3, 1, 2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

In [186]:
arr[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [192]:
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [194]:
arr[1,3]

7

In [195]:
arr[[1,3]]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [198]:
arr[:2, 3:]

array([[3],
       [7]])

In [201]:
arr[[1], [0,3,1,2]]

array([4, 7, 5, 6])

In [209]:
arr[[1, 5, 7, 2]][:, [0 ,3,1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [206]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [210]:
arr[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [211]:
arr[:2][1:]

array([[4, 5, 6, 7]])

In [213]:
arr[1][2]

6

In [214]:
arr[1,2]

6

In [215]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [216]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [217]:
np.dot(arr.T, arr)

array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])

In [218]:
arr @ arr.T

array([[  14,   38,   62,   86,  110,  134,  158,  182],
       [  38,  126,  214,  302,  390,  478,  566,  654],
       [  62,  214,  366,  518,  670,  822,  974, 1126],
       [  86,  302,  518,  734,  950, 1166, 1382, 1598],
       [ 110,  390,  670,  950, 1230, 1510, 1790, 2070],
       [ 134,  478,  822, 1166, 1510, 1854, 2198, 2542],
       [ 158,  566,  974, 1382, 1790, 2198, 2606, 3014],
       [ 182,  654, 1126, 1598, 2070, 2542, 3014, 3486]])

In [221]:
arr2 = np.arange(16).reshape(4,4)

In [222]:
arr2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [224]:
np.dot(arr2.T, arr2)

array([[224, 248, 272, 296],
       [248, 276, 304, 332],
       [272, 304, 336, 368],
       [296, 332, 368, 404]])

In [225]:
arr2 @ arr2.T

array([[ 14,  38,  62,  86],
       [ 38, 126, 214, 302],
       [ 62, 214, 366, 518],
       [ 86, 302, 518, 734]])

In [226]:
arr2.T @ arr2

array([[224, 248, 272, 296],
       [248, 276, 304, 332],
       [272, 304, 336, 368],
       [296, 332, 368, 404]])

In [228]:
a = np.array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])


In [229]:
a

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [230]:
a.swapaxes

<function ndarray.swapaxes>

In [231]:
a

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [232]:
a.swapaxes(0,1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [233]:
a.swapaxes(1,0)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [239]:
a.swapaxes(-1,0)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [240]:
np.random.standard_normal(size = (4,4))

array([[-0.30135878,  0.08891019,  2.09720644, -1.10048125],
       [-1.14135523,  0.4430817 ,  0.58474619, -0.37544811],
       [ 0.1426068 , -0.55871746, -0.93756317,  1.93802616],
       [-1.07116974,  1.11398891, -0.29547793,  1.04009074]])

In [242]:
np.random.permutation(10)

array([3, 0, 6, 5, 9, 1, 8, 4, 2, 7])

In [253]:
gibber = np.arange(10, dtype = 'int64')

In [254]:
gibber

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [258]:
np.sqrt(gibber)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [259]:
np.exp(gibber)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [261]:
rng = np.random.default_rng(seed=12345)

In [262]:
type(rng)

numpy.random._generator.Generator

In [266]:
rng

Generator(PCG64) at 0x7FED334767A0

In [265]:
x = rng.standard_normal(8)

In [267]:
y = rng.standard_normal(8)

In [277]:
x

array([ 0.36105811, -1.95286306,  2.34740965,  0.96849691, -0.75938718,
        0.90219827, -0.46695317, -0.06068952])

In [278]:
y

array([ 0.78884434, -1.25666813,  0.57585751,  1.39897899,  1.32229806,
       -0.29969852,  0.90291934, -1.62158273])

In [279]:
np.maximum(x,y)

array([ 0.78884434, -1.25666813,  2.34740965,  1.39897899,  1.32229806,
        0.90219827,  0.90291934, -0.06068952])

In [283]:

sign = np.sign(y)

In [284]:
sign

array([ 1., -1.,  1.,  1.,  1., -1.,  1., -1.])

In [285]:
np.rint(y)

array([ 1., -1.,  1.,  1.,  1., -0.,  1., -2.])

In [286]:
np.modf(y)

(array([ 0.78884434, -0.25666813,  0.57585751,  0.39897899,  0.32229806,
        -0.29969852,  0.90291934, -0.62158273]),
 array([ 0., -1.,  0.,  1.,  1., -0.,  0., -1.]))

In [287]:
points = np.arange(-5, 5, 0.01)

In [288]:
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [289]:
xs, ys = np.meshgrid(points, points)

In [290]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [291]:
arr = np.arange(16).reshape(4,4)

In [292]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [293]:
arr.sum(axis=1)

array([ 6, 22, 38, 54])

In [294]:
arr.mean()

7.5

In [295]:
sum=0
for i in range(16):
    sum += i
print(sum/len(range(16)))
    

7.5


In [296]:
24/4

6.0

In [297]:
arr.mean(axis = 0)

array([6., 7., 8., 9.])

In [298]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [299]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [300]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [301]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [302]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [312]:
arr = rng.standard_normal(100)

In [313]:
(arr > 0).sum()

50

In [314]:
(arr <= 0).sum()

50

In [316]:
arr = np.arange(10)

In [322]:
arr = np.random.permutation(arr)

In [319]:
arr

array([7, 8, 6, 5, 1, 3, 9, 4, 2, 0])

In [323]:
np.sort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [324]:
arr

array([5, 7, 9, 6, 8, 2, 4, 3, 1, 0])

In [325]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])

In [326]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [328]:
names.unique()

AttributeError: 'numpy.ndarray' object has no attribute 'unique'